### ISSUE TITLE
Add reorder util

### ISSUE THREAD

**Issue by quolpr** [rocicorp/fractional-indexing#16]
Hey! Thank you for the lib, very helpful. I have a problem — I miss the reorder function. 

I am using https://www.framer.com/motion/reorder/ , and on order change it returns a new array of items, like: 
before reorder — `[{id: 1, orderToken: 'a0'}, {id: 2, orderToken: 'a1'}, {id: 3, orderToken: 'a2'}]`
after reorder — `[{id: 2, orderToken: 'a1'}, {id: 1, orderToken: 'a0'}, {id: 3, orderToken: 'a2'}]`

Would it be possible to provide such a function that will provide new order tokens? Like, maybe `applyReorder(beforeOrders: string[], afterOrders: string[]) => string[]`

**Comment by quolpr** [comment]
Or maybe you have advice on how it can be done 😅

**Comment by arv** [comment]
Not totally clear what you want here but could you generate a whole new set of `orderTokens` using `generateNKeysBetween` and update all the elements in that array?

```ts
let arr = ...
const newOrderTokens = generateNKeysBetween(null, null, arr.length);
arr = arr.map(({id}, i) => ({id, orderToken: newOrderTokens[i]}))
```

Other options include figuring out how the elements were moved and only update those but it requires more work (at least more complicated work).

**Comment by arv** [comment]
Look into some of the editing distance algorithms...

One way to do this would be to compute the diff between state A and B. This would give you inserts and removes. For an insert you create the new orderToken between the before and after. For removal you do not need to do anything since all removals are also inserted. When there are consecutive inserts you could use generateNKeysBetween but I don't know if it is worth extra complications.

For example:

1.txt
```
Alice
Bob
Charlie
Dave
Eve
Frank
```
2.txt
```
Alice
Eve
Bob
Charlie
Dave
Frank
```
```sh
$ diff -u 1.txt 2.txt
--- 1.txt	2023-03-30 10:09:40
+++ 2.txt	2023-03-30 10:16:00
@@ -1,6 +1,6 @@
 Alice
+Eve
 Bob
 Charlie
 Dave
-Eve
 Frank
```

Here you can see that `Eve` was inserted between `Alice` and `Bob` so its order key should be between `Alice` and `Bob`'s order keys.

I hope that gives you some ideas.
